### ISSUE TITLE
[clang] error: no matching member function for call to '_save_tiff'

### ISSUE THREAD

**Issue by thierry-FreeBSD** [dtschump/CImg#42]
Trying to compile with clang (version 3.4.1 on FreeBSD), it fails:

In file included from use_tiff_stream.cpp:52:
In file included from ../CImg.h:9196:
../plugins/tiff_stream.h:105:39: error: no matching member function for call to '_save_tiff'
      cimg_forZ(*this,z) get_slice(z)._save_tiff(tif,z,compression_type,0,0);
                         ~~~~~~~~~~~~~^~~~~~~~~~
use_tiff_stream.cpp:70:39: note: in instantiation of member function 'cimg_library::CImg<unsigned short>::save_tiff' requested here
  CImg<unsigned short> imgOut = imgIn.save_tiff(&outFile, 2U);
                                      ^
../CImg.h:48567:20: note: candidate function template not viable: requires 7 arguments, but 5 were provided
    const CImg<T>& _save_tiff(TIFF *tif, const unsigned int directory, const unsigned int z, const t& pixel_t,
                   ^
../CImg.h:48625:20: note: candidate function not viable: requires 6 arguments, but 5 were provided
    const CImg<T>& _save_tiff(TIFF *tif, const unsigned int directory, const unsigned int z,

Remark: it's OK with Gcc 4.8.

**Comment by dtschump** [comment]
Thanks for reporting.
Commit : https://github.com/dtschump/CImg/commit/657d88afaeaf75e1cfc37b4d2b67c36386f2b950
should fix the issue.

**Comment by thierry-FreeBSD** [comment]
Great, this fixed it!
