### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Overdrivr** [dtschump/CImg#26]
Hello,
Using gradle build system, with MinGW gcc 4.8.1, on windows 7
I get the following error message

```
See file:///C:/Users/Documents/GitHub/ZNoise/build/tmp/compileDebugExamplesExecutableExamplesCpp/output.txt for all output for compileDebugExamplesExecutableExamplesCpp.
compiling example_01.cpp failed.
In file included from C:\Users\Documents\GitHub\ZNoise\src\examples\cpp\example_01.cpp:2:0:
C:\Users\Documents\GitHub\ZNoise\src\cimg\headers/CImg.h: In function 'FILE* cimg_library::cimg::fopen(const char*, const char*)':
C:\Users\Documents\GitHub\ZNoise\src\cimg\headers/CImg.h:4725:35: error: '_fileno' was not declared in this scope
           if (_setmode(_fileno(res),0x8000)==-1) res = 0;
```
This is my compiler flags
```
-x
c++
-c
-std=c++11
-I
C:\\Users\\Documents\\GitHub\\ZNoise\\src\\examples\\headers
-I
C:\\Users\\Documents\\GitHub\\ZNoise\\src\\cimg\\headers
-I
C:\\Users\\Documents\\GitHub\\ZNoise\\src\\znoise\\headers
-m32
```

Any idea on what is going on ?

**Comment by dtschump** [comment]
Not sure which version of CImg you are using, the line number does not correspond with the current version (latest in git). I have line 4826 instead.
I don't have this error when I compile with MinGW gcc 4.9.2, so I'm not sure this is related to CImg.
Maybe you could try this : http://stackoverflow.com/questions/22081825/compiling-cimg-with-c0x-and-mingw ?

**Comment by Overdrivr** [comment]
Ok I found the solution
I've made the update first, but I still had the issue afterward.

I made a stupid mistake in my gradle.build file.
I put compiler flags for the cimg module but since it's header-only those flags where not taken into account.

Now I have a linking issue but I am not sure it is related. I will investigate and open another ticket if needed.

Thank you for your support, great library btw
